-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."facilitator_roles" add column "facillatorid" bigserial
--  not null;
